### ISSUE TITLE
Use requests

### ISSUE THREAD

**Issue by shahzzzam** [jeelpatel007/Profanity_Checker#1]
_urllib is so 1990's._
- You could use `requests` instead.
- [This](https://github.com/jeelpatel007/Profanity_Checker/blob/master/profanity_chk.py#L16)  and the next line could be done by `requests` as:

``` python
r = requests.get('http://www.wdyl.com/profanity', params={'q': text_to_check})
if r.text == 'true':  # or json.loads(r.text) == True, I guess
    print('Profanity alert')
```
##### Aside:

> Its a good practice to do this:
> 
> ``` python
> if __name__ == 'main':
>    read_text()
> ```
> 
> Instead of just calling read_text()

**Comment by jeelpatel007** [comment]
@samarthmshah Thanks for checking out my code. I should have thought to use `request` instead of `urllib`
- [x] Please find updated code [here](https://github.com/jeelpatel007/Profanity_Checker/blob/master/profanity_chk.py)
